export enum NotificationType {
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  ADD_PRIVATE_ROOM = 'ADD_PRIVATE_ROOM',
  DELETE_PRIVATE_ROOM = 'DELETE_PRIVATE_ROOM',
  GAME_REQUEST = 'GAME_REQUEST',
  GLOBAL_MESSAGE = 'GLOBAL_MESSAGE'
}
